refactor postgres build into multiple steps

diff --git a/.github/workflows/build-db.yml b/.github/workflows/build-db.yml
--- a/.github/workflows/build-db.yml
+++ b/.github/workflows/build-db.yml
@@ -42,48 +42,20 @@ jobs:
       - name: 'Set up Cloud SDK'
         uses: 'google-github-actions/setup-gcloud@v0'
 
-      - name: Download icu/hosp demo and load into PostgreSQL
+      - name: Download demo data from GCP
         run: |
           echo "Downloading MIMIC-IV demo from GCP."
           gsutil -q -u $PROJECT_ID -m cp -r gs://mimic-iv-archive/v2.0/demo ./
-
-          echo "Loading data into psql."
-          psql -q -h $POSTGRES_HOST -U postgres -f mimic-iv/buildmimic/postgres/create.sql
-          psql -q -h $POSTGRES_HOST -U postgres -v mimic_data_dir=demo -f mimic-iv/buildmimic/postgres/load_gz.sql
-          echo "Validating build."
-          psql -h $POSTGRES_HOST -U postgres -f mimic-iv/buildmimic/postgres/validate_demo.sql > results
-          
-          # if we find "FAILED", then we did not pass the build
-          if grep -F -q "FAILED" results; then
-            echo "Failed the following row counts:"
-            head -n 1 results
-            grep "FAILED" results
-            exit 1
-          else
-            echo "Built and loaded demo data successfully."
-            cat results
-          fi
-
         env:
-          # The hostname used to communicate with the PostgreSQL service container
-          POSTGRES_HOST: postgres
-          PGPASSWORD: postgres
-          # The default PostgreSQL port
-          POSTGRES_PORT: 5432
           PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
 
-      - name: Download ed demo and load into PostgreSQL
+      - name: Load icu/hosp data into PostgreSQL
         run: |
-          echo "Downloading MIMIC-IV-ED demo from GCP."
-          gsutil -q -u $PROJECT_ID -m cp -r gs://mimic-iv-archive/v2.0/demo/ed ./
-          MIMIC_DATA_DIR=`pwd`/ed
-
           echo "Loading data into psql."
-          cd mimic-iv-ed/buildmimic/postgres
-          psql -q -h $POSTGRES_HOST -U postgres -f create.sql
-          psql -q -h $POSTGRES_HOST -U postgres -v mimic_data_dir=$MIMIC_DATA_DIR -f load_gz.sql
+          psql -q -h $POSTGRES_HOST -U postgres -f ${BUILDCODE_PATH}/create.sql
+          psql -q -h $POSTGRES_HOST -U postgres -v mimic_data_dir=demo -f ${BUILDCODE_PATH}/load_gz.sql
           echo "Validating build."
-          psql -h $POSTGRES_HOST -U postgres -f validate_demo.sql > results
+          psql -h $POSTGRES_HOST -U postgres -f ${BUILDCODE_PATH}/validate_demo.sql > results
           
           # if we find "FAILED", then we did not pass the build
           if grep -F -q "FAILED" results; then
@@ -102,7 +74,34 @@ jobs:
           PGPASSWORD: postgres
           # The default PostgreSQL port
           POSTGRES_PORT: 5432
-          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
+          BUILDCODE_PATH: mimic-iv/buildmimic/postgres
+
+      - name: Load ed data into PostgreSQL
+        run: |
+          echo "Loading data into psql."
+          psql -q -h $POSTGRES_HOST -U postgres -f ${BUILDCODE_PATH}/create.sql
+          psql -q -h $POSTGRES_HOST -U postgres -v mimic_data_dir=demo/ed -f ${BUILDCODE_PATH}/load_gz.sql
+          echo "Validating build."
+          psql -h $POSTGRES_HOST -U postgres -f ${BUILDCODE_PATH}/validate_demo.sql > results
+          
+          # if we find "FAILED", then we did not pass the build
+          if grep -F -q "FAILED" results; then
+            echo "Failed the following row counts:"
+            head -n 1 results
+            grep "FAILED" results
+            exit 1
+          else
+            echo "Built and loaded demo data successfully."
+            cat results
+          fi
+
+        env:
+          # The hostname used to communicate with the PostgreSQL service container
+          POSTGRES_HOST: postgres
+          PGPASSWORD: postgres
+          # The default PostgreSQL port
+          POSTGRES_PORT: 5432
+          BUILDCODE_PATH: mimic-iv-ed/buildmimic/postgres
 
   build-mimic-iv-mysql:
     runs-on: ubuntu-22.04
